#!/usr/bin/env python2.5
import os.path, sys
from countershape import doc, blog

class QBlag(doc.CSDoc):
    def getParser(self):
        parser = doc.CSDoc.getParser(self)
        parser.add_option("-r", "--rewrite",
                          action="store_true", dest="rewrite", default=False,
                          help="Rewrite changed posts.")
        parser.add_option("-l", "--list",
                          action="store_true", dest="lst", default=False,
                          help="List all posts.")
        return parser

    def run(self, root, app, options, args):
        if options.rewrite:
            lst = filter(
                    lambda x: isinstance(x, blog.Post), root.preOrder()
                )
            for i in lst:
                if i.changed:
                    print >> sys.stderr, "Rewriting %s"%i.src
                    i.rewrite()
        elif options.lst:
            lst = filter(
                    lambda x: isinstance(x, blog.Post), root.preOrder()
                )
            for i in lst:
                print "%s:"%i.time, i.title
        else:
            doc.CSDoc.run(self, root, app, options, args)



def main():
    c = QBlag()
    c.main()

if __name__ == "__main__":
    main()
